### ISSUE TITLE
Unable to create non-existent notes successfully with 'jottem edit'

### ISSUE THREAD

**Issue by JoelWi** [dogue/jottem#3]
Using `jottem edit {path/to/note/that/doesnt/exist}` returns various errors (depending on first run or subsequent runs)

![image](https://github.com/dogue/jottem/assets/12691296/d9f6afb6-321a-4826-ac6d-aafe9ce7ddc4)

However it looks like the note is still created, but is inaccessible by Jottem

![image](https://github.com/dogue/jottem/assets/12691296/82a03f3a-556e-4673-9332-6300db103575)

Deleting .cache/jottem appeared to make no difference, and I could still re-produce the above:
![image](https://github.com/dogue/jottem/assets/12691296/2375bf3c-f440-4f91-b451-fc34a2c08292)

This was done on WSL2 Ubuntu 20.04

**Comment by dogue** [comment]
The first error appears to originate from trying to open the index database twice at once. I will investigate this.

The subsequent error and inability to access the note is due to how Jottem uses the index to retrieve absolute paths in order to avoid traversing the filesystem each run.

**Comment by dogue** [comment]
I suspect this is due to `utils::get_note()` calling `utils::create_note()`, both of which call `Index::open()`, resulting in an IO lock error.

**Comment by dogue** [comment]
Hotfix pushed to main.

Keeping this open until a "proper" fix is in place.

**Comment by dogue** [comment]
Closing this as solved with the hotfix. Refactor incoming before the next release to make testing easier and more robust.
